### ISSUE TITLE
Make the docs yellow

### ISSUE THREAD

**Issue by hugovk** [AlexWaygood/cpython#16]
### Has this already been discussed elsewhere?

No response given

### Proposal:

```python
# Add a code block here, if required
```

**Comment by hugovk** [comment]
Hmm, https://github.com/AlexWaygood/cpython/issues/new?assignees=&labels=type-feature&projects=&template=feature.yml can be submitted without selecting one of the other dropdowns:

<img width="552" alt="image" src="https://github.com/AlexWaygood/cpython/assets/1324225/fb4bca31-4ac1-428a-9983-615d88db135f">

**Comment by hugovk** [comment]
How is it if we remove "No response given"?

**Comment by AlexWaygood** [comment]
> Hmm, https://github.com/AlexWaygood/cpython/issues/new?assignees=&labels=type-feature&projects=&template=feature.yml can be submitted without selecting one of the other dropdowns:

Yup. There doesn't seem to be a way around that, unfortunately. I still think it's marginally better than checkboxes, though -- looks like the checkboxes are [annoying some of our core devs](https://github.com/python/cpython/issues/108021) :)

> How is it if we remove "No response given"?

Then it defaults to the first option in the list ("I have already discussed this proposal on Discourse"), which seems worse?

**Comment by hugovk** [comment]
Yes, I think defaulting to that first option would be worse.

Maybe the checkboxes would be better than if we start getting "No response" here? 

You could also ask the core dev if they prefer the original checkboxes or this new dropdown.

I'm fine with trying either: it's good to test out and iterate 👍
