### ISSUE TITLE
It's too hot in the UK right now

### ISSUE THREAD

**Issue by AlexWaygood** [AlexWaygood/cpython#19]
# Bug report

### Bug description:

I suggest we do this:

```python
solve_global_warming()
```

### CPython versions tested on:

3.8, 3.10, 3.12

**Comment by AA-Turner** [comment]
A balmy 27° here!

**Comment by AlexWaygood** [comment]
> A balmy 27° here!

+1, literally: 28° here 🥵

**Comment by hugovk** [comment]
Welcome to Finland for 18°!

**Comment by AA-Turner** [comment]
> literally: 28° here 🥵

Time for a Mr Whippy 🍧

**Comment by AlexWaygood** [comment]
Still too hot :( maybe out of scope tho
