### ISSUE TITLE
Solve the UK heatwave

### ISSUE THREAD

**Issue by AlexWaygood** [AlexWaygood/cpython#20]
# Feature or enhancement

### Proposal:

Python should add a new feature to solve the heatwave in the UK

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by AA-Turner** [comment]
``import air.conditioning``

**Comment by sobolevn** [comment]
Weather right now in my hometown:
![IMG-20230904-WA0005 (1)](https://github.com/AlexWaygood/cpython/assets/4660275/b13237eb-0c3e-4652-8d99-ffb4cb812207)
![IMG-20230904-WA0007 (1)](https://github.com/AlexWaygood/cpython/assets/4660275/4434dd38-92f5-4df7-9fe8-ff99e9d85117)

**Comment by AlexWaygood** [comment]
> AA

ping me when the PEP is ready, i will sponsor it

**Comment by AA-Turner** [comment]
April Fools PEPs are always such fun! (27°C today less fun)
